# Generated by Django 4.2.1 on 2023-06-16 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='type',
            field=models.CharField(default='', max_length=200, verbose_name='文章分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='join_date',
            field=models.DateField(default=datetime.date(2023, 6, 16), verbose_name='加入时间'),
        ),
    ]
